# Generated by Django 4.2.4 on 2024-06-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpesa", "0003_alter_lnmonline_merchantrequestid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="C2BPayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "TransactionType",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("TransID", models.CharField(blank=True, max_length=15, null=True)),
                ("TransTime", models.CharField(blank=True, max_length=15, null=True)),
                ("TransAmount", models.FloatField(blank=True, default=20, null=True)),
                (
                    "BusinessShortCode",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "BillRefNumber",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "InvoiceNumber",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "OrgAccountBalance",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                (
                    "ThirdPartyTransID",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("MSISDN", models.CharField(blank=True, max_length=12, null=True)),
                ("FirstName", models.CharField(blank=True, max_length=20, null=True)),
                ("MiddleName", models.CharField(blank=True, max_length=20, null=True)),
                ("LastName", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
