# Generated by Django 4.2.4 on 2024-06-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mpesa", "0004_c2bpayments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="c2bpayments",
            name="TransAmount",
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
